#!/bin/bash
#argument : nom_fichier new_taille new_mode new_date

fichier=$(./appel_lecture $1) #recherche dans le journal

IFS='|'
read -a tab <<< "$fichier" #permet la recuperation de l'indice de mofification présent en début de chaine de caractere

#retablissement du separateur par défaut
IFS=' '
nouveau="$1|$2|$3|$4" #définition des nouveaux arguements à insérer.
fichier="${tab[1]}|${tab[2]}|${tab[3]}|${tab[4]}" #composition du nom de l'ancien fichier

if [[ ${tab[0]} -eq 1 ]]
then
  sed -i "s,$fichier,$nouveau,g" journal #remplacement par recherche
else
  echo "$nouveau" >> journal #écriture en fin
fi


