#!/bin/bash

function validite () #vérifie le répertoire, existence, unicité
{
  local rep=$1
  local valide=0
  local occurence=0
  local chemin_rep=""
  local indice
  local indice_max
  while [[ $valide -eq 0 ]]
  do
    occurence=$(find /home -type d -name "$rep" | wc -l)
    if [[ $occurence -eq 0 ]]
    then
      echo "Le repèrtoire spécifié n'existe pas." > /dev/stderr
      echo "Veuillez ressaisir un nom existant" > /dev/stderr
      read rep
    elif [[ $occurence -eq 1 ]]
    then
       valide=1
       chemin_rep=$(find /home -type d -name "$rep")
    else
      echo "Plusieurs repertoires rencontrés : " > /dev/stderr
      find /home -type d -name "$rep" > /dev/stderr
      indice_max=$(find /home -type d -name "$rep" | wc -l)
      echo "Veuillez spécifier le chemin que vous voulez sélectionner : 1,2 ou 3 ....." > /dev/stderr
      read indice
      while [[ $indice -lt 1 || $indice -gt $indice_max ]]
      do
        echo "Le nombre saisi doit se situer entre 1 et $indice_max." > /dev/stderr
        echo "Veuillez ressaisir l'indice :" > /dev/stderr
        read indice
      done
      chemin_rep=$(find /home -type d -name "$rep" | head -$indice | tail -1)
      valide=1
    fi
  done
  echo $chemin_rep
}

function sous_validite ()
{
  local acces1=$1
  local acces2=$2
  local test=0
  local test_rep
  while [[ test -eq 0 ]]
  do
    echo "Veuillez indiquer le sous-répertoire" > /dev/stderr
    read test_rep
    test_rep=$(echo $test_rep | sed -e "s,^/,,")
    test_rep=$(echo $test_rep | sed -e "s,^,/,")
    acces1=$1
    acces2=$2
    acces1+=$test_rep
    acces2+=$test_rep
    if [ -e $acces1 ] || [ -e $acces2 ]
    then
      test=1
      echo $test_rep
    else
      echo "Sous dossier inexistant " > /dev/stderr
    fi
  done
}

function branche()
{
  local reponse="y"
  local sous_rep
  echo "Voulez vous synchroniser/supprimer tout le répertoire (y/n)" > /dev/stderr
  read reponse
  if [[ $reponse = "y" ]]
  then
    echo "/"
  else
    sous_rep=$(sous_validite $1 $2)
    echo $sous_rep
  fi

}
#création ou modification des droits du journal
user=$(whoami)
journal="/home/$user/.journal"

if [ -f $journal ]
then
  chmod +rw $journal
else
  touch $journal
fi

echo "Saisir le nom du premier répertoire"
read  rep1

chemin1=$(validite $rep1) #vérifie que le répertoire 1 existe

echo "Saisir le nom du second répertoire"
read  rep2

chemin2=$(validite $rep2) #vérifie que le répertoire 2 existe

chemin1=$(echo $chemin1 | sed "s,/$,,")
chemin2=$(echo $chemin2 | sed "s,/$,,")


sous_repertoire=$(branche $chemin1 $chemin2) #vérifie que le sous_dossier existe
sous_repertoire=$(echo $sous_repertoire | sed "s,/$,,") #mise en forme
sous_repertoire=$(echo $sous_repertoire | sed "s,$,/,")


echo "Voulez vous synchroniser (1) ou supprimer des repertoires (2) ?"
read choix
if [[ choix -eq 1 ]]
then
  ./synchronizer.sh $chemin1 $chemin2 $sous_repertoire
elif [[ choix -eq 2 ]]
then
  ./deleter $chemin1 $chemin2 $sous_repertoire
else
  echo "choix incorrect"
fi

echo "Arrêt du programme"